add check downloader jar file in CI

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -44,3 +44,12 @@ steps:
   displayName: Run Tests
   env:
     DISPLAY: ':99.0'
+
+- bash: |
+    echo ">>> Get the downloader release"
+    npm run get-downloader-release
+    if [ -f "checker-framework-languageserver-downloader.jar" ]; then
+        echo "Download successfully."
+    else
+        echo "Download failed." && exit 1
+    fi
